export const REQUEST_COMMON_SUCCESS_RESPONSE =
  'REQUEST_COMMON_SUCCESS_RESPONSE';
export const REQUEST_COMMON_ERROR_RESPONSE = 'REQUEST_COMMON_ERROR_RESPONSE';
export const SET_LANG = 'SET_LANG';
export const SET_PLAY = 'SET_PLAY';
export const SET_CONNECTION = 'SET_CONNECTION';
export const WEEK_PROGRAM_DATA_REQUEST = 'PROGRAMWEEK_PROGRAM_DATA_REQUESTS_DATA';
export const WEEK_PROGRAM_DATA_SUCCESS = 'WEEK_PROGRAM_DATA_SUCCESS';
export const WEEK_PROGRAM_DATA_ERROR = 'WEEK_PROGRAM_DATA_ERROR';

export const NOW_PROGRAM_DATA_REQUEST = 'NOW_PROGRAM_DATA_REQUESTS_DATA';
export const NOW_PROGRAM_DATA_SUCCESS = 'NOW_PROGRAM_DATA_SUCCESS';
export const NOW_PROGRAM_DATA_ERROR = 'NOW_PROGRAM_DATA_ERROR';

export const CONTACT_FORM_REQUEST = 'CONTACT_FORM_REQUESTS';
export const CONTACT_FORM_SUCCESS = 'CONTACT_FORM_SUCCESS';
export const CONTACT_FORM_ERROR = 'CONTACT_FORM_ERROR';

